os: osx
dist: trusty
language: generic

sudo: false

before_install:
 - brew update
 - which python3 || brew install python@3.8
 - pip3 install numpy

matrix:
  include:
    - name: "HEAD with homebrew python"
      install: travis_wait 180 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3
      env:
        - version=HEAD HOMEBREW_DEVELOPER=1
    - name: "Stable with homebrew python"
      install: travis_wait 180 brew install ./Formula/rdkit.rb --build-from-source --with-python3
      env:
        - version=current HOMEBREW_DEVELOPER=1
