os: osx
dist: trusty
language: generic

sudo: false

# See https://stackoverflow.com/questions/39930171/cache-brew-builds-with-travis-ci
cache:
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - brew cleanup

before_install:
 - brew update
 - brew install python@3.8
 - which python38
 - python38 -m pip install numpy

matrix:
  include:
    - name: "HEAD with homebrew python"
      install: travis_wait 180 brew install ./Formula/rdkit.rb --HEAD --build-from-source --with-python3
      env:
        - version=HEAD HOMEBREW_DEVELOPER=1
    - name: "Stable with homebrew python"
      install: travis_wait 180 brew install ./Formula/rdkit.rb --build-from-source --with-python3
      env:
        - version=current HOMEBREW_DEVELOPER=1
